apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-python
spec:
  destination:
    name: ''
    namespace: dev
    server: 'https://kubernetes.default.svc'
  source:
    path: config
    repoURL: 'https://github.com/lugosidomotor/devops-task.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
